nodes:
  - id: front_door_switch
    name: Front door light switch
    config: fgs_223.yaml
    node: 4

  - id: socket1
    name: Mains socket
    config: tkb_tz68.yaml
    node: 5

switches:
  - id: outside_light
    name: Outside light
    nodeid: front_door_switch
    endpoint: 1

  - id: void_light
    name: Void light
    nodeid: front_door_switch
    endpoint: 2

  - id: mains_switch
    name: Mains switch
    nodeid: socket1
    endpoint: 1
