nodes:
  - id: front_door_switch
    name: Front door light switch
    config: fgs_223.yaml
    node: 4

switches:
  - id: outside_light
    name: Outside light
    nodeid: front_door_switch
    endpoint: 1

  - id: void_light
    name: Void light
    nodeid: front_door_switch
    endpoint: 2
