nodes:
  - id: front_door_lights
    name: Front door lights
    config: fgs_223.yaml
    node: 4

  - id: socket1
    name: "Mains socket #1"
    config: tkb_tz68.yaml
    node: 5

  - id: overstair_light
    name: Over stair light
    config: fgd_212.yaml
    node: 6

switches:
  - id: outside_light
    name: Outside light
    nodeid: front_door_lights
    endpoint: 1

  - id: void_light
    name: Void light
    nodeid: front_door_lights
    endpoint: 2

  - id: socket1
    name: "Mains socket #1"
    nodeid: socket1
    endpoint: 1

dimmers:
  - id: overstair_light
    name:  Over stair light
    nodeid: overstair_light
    endpoint: 1
