nodes:
  - id: front_door_lights
    name: Front door lights
    config: fgs_223.yaml
    node: 4

  - id: socket1
    name: Mains socket
    config: tkb_tz68.yaml
    node: 5

switches:
  - id: outside_light
    name: Outside light
    nodeid: front_door_lights
    endpoint: 1

  - id: front_door_light
    name: Front door light
    nodeid: front_door_lights
    endpoint: 2

  - id: mains_switch1
    name: Mains switch
    nodeid: socket1
    endpoint: 1
